# -*- coding: utf-8 -*-
#
# This file is part of DoJSON
# Copyright (C) 2015, 2016 CERN.
# Copyright (C) 2020 Graz University of Technology.
#
# DoJSON is free software; you can redistribute it and/or modify
# it under the terms of the Revised BSD License; see LICENSE file for
# more details.

sudo: false

language: python

env:
  - REQUIREMENTS=lowest
  - REQUIREMENTS=release

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy"

matrix:
  allow_failures:
    - python: 3.8
    - python: pypy

before_install:
  - "travis_retry pip install --upgrade pip setuptools"
  - "travis_retry pip install twine wheel coveralls requirements-builder"
  - "requirements-builder -e all --level=min setup.py > .travis-lowest-requirements.txt"
  - "requirements-builder -e all --level=pypi setup.py > .travis-release-requirements.txt"

install:
  - "travis_retry pip install -r .travis-${REQUIREMENTS}-requirements.txt"
  - "travis_retry pip install -e .[docs,tests]"

script:
  - "./run-tests.sh"

after_success:
  - coveralls

notifications:
  email: false
